export const CART_ACTION_TYPES = {
  IS_CART_OPEN: 'cart/IS_CART_OPEN',
  SET_ITEM_TO_CART: 'cart/SET_ITEM_TO_CART',
  REMOVE_ITEM_TO_CART: 'cart/REMOVE_ITEM_TO_CART',
  CLEAR_ITEM_FROM_CART: 'cart/CLEAR_ITEM_FROM_CART',
  TOTAL_CART_ITEMS: 'cart/TOTAL_CART_ITEMS',
};
